[project]
name = "lecture-13-capstone"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "dotenv>=0.9.9",
    "openai>=1.98.0",
    "pdf2image>=1.17.0",
    "python-dotenv>=1.1.1",
]
